### PR TITLE
Improve newPaint(): remove redundant comparaison, avoid needless closures & temp array, remove dead code

### PR DESCRIPTION
**Pull request by PaulCapron**
Please see the commit messages for more info about the *why* and *how*.

Looking at the diff for **`index.js`** may be the best to grasp real code changes. 
Some whitespace issues messed up the `index.ts` diff a bit :-(

### CODE REVIEW

**Comment by nbarkhina** [comment]
Agreed on the "repeated if statement" and the "remove variables". In terms of the improved efficiency is there any way to still use a forEach instead of a for loop? I like that style better because then it saves us from having the extra line of code - "let element = elements[i];"

**Comment by PaulCapron** [comment]
About using a closure instead of a `for` loop: one idea is to use **jQuery `each`** method (https://api.jquery.com/each/). Another to use `Array.from` (but that’s ES2015) to transform the jQuery object to a plain array. Or to use `for … of`.
I can rewrite the code to use `each`, are you up for it?

**Comment by nbarkhina** [comment]
sure, actually what you can do is just -

let elements = $("[tetris-block]").toArray();

that would immediately cast it to a HTMLElement[] so then you can change it back to elements.forEach(element => {})

**Comment by PaulCapron** [comment]
I’ve force-pushed my branch with changed, updated commits. 

`newPaint()` nows uses jQuery `toArray`, as you suggested. The code looks like this:
```javascript
$("[tetris-block]").toArray().forEach(element => {
    …
}
```

**Comment by nbarkhina** [comment]
Looks good Thanks

**Pull request merged**
